import { announcement } from "./announcement"
import { employee } from "./employee"
import { blogPosts } from "./blog_posts"
import { cards } from "./cards"
import {global_navbar} from "./global-navbar"
import { global_sidebar } from "./global_sidebar"
import { global_sidebar_components } from "./global_sidebar_components"
import { homepage } from "./homepage"
import { homPagee } from "./homePagee"
import { local_navbar } from "./localNavbar"
import { myFinancesPage } from "./myFinancesPage"
import { myProfilePage } from "./myProfilePage"
import { myTeam } from "./myTeam"
import { navigationBar } from "./navigation_bar"
import { orgPage } from "./orgPage"
import { quickAccess } from "./quickAccess"
import { birthday } from "./birthday"
import { workAnniversary } from "./workAnniversary"
import { poll } from "./poll"
import { newJoiners } from "./newJoiners"
import { subComponents } from "./subComponent"
import { sideBar } from "./sideBar"
import { subComponentsa } from "./subComponentsa"
export const schemaTypes = [global_navbar,cards,homepage,employee,global_sidebar_components,myProfilePage,local_navbar,orgPage,myTeam,myFinancesPage,navigationBar,blogPosts,homPagee,quickAccess,announcement,birthday,workAnniversary,poll,newJoiners,subComponents,sideBar]


